### PR TITLE
fixed deprecations of event dispatching

### LINKED ISSUE #8: Event dispatch deprecations
Need to fix event dispatch deprecations:
 - \Ivory\GoogleMap\Helper\PlaceAutocompleteHelper::doRender
 - \Ivory\GoogleMap\Helper\MapHelper::doRender
 - \Ivory\GoogleMap\Helper\StaticMapHelper::render
 - \Ivory\GoogleMap\Helper\Subscriber\Image\StaticSubscriber::handle

### PR DESCRIPTION
**Pull request by thorau**
Should fix #8

### CODE REVIEW

**Comment by bresam** [comment]
Hi @thorau Thank you very much for that PR.

Have you already checked for compatibility with the oldest dependencies possible?
Like v3 symfony/dispatcher

I've seen a lot of packages which updated to a solution with an if/else statement which checks for the actual system requirement by an instanceof check.

I will start fixing unittests on that project too and than check and merge.

**Comment by thorau** [comment]
@bresam Thanks for your hint. I will check. I think the LegacyEventDispatcherProxy (https://github.com/symfony/event-dispatcher/blob/4.4/LegacyEventDispatcherProxy.php) will do the job.

**Comment by thorau** [comment]
@bresam I added the LegacyEventDispatcherProxy to ensure backward compatibility. Please have a look.

**Comment by bresam** [comment]
Thank you for your contribution 🎉

**Pull request merged**
