### PR TITLE
feat: add support for symfony 6

### PR DESCRIPTION
**Pull request by Chris53897**
temp, see
https://github.com/bresam/ivory-serializer/pull/4

- fix ci deprecations
- add testruns for php 8.1 and 8.2
- fix warning for uniqid() with null
- make one test runable in phpunit 8 and 9
- adjust phpunit config file to pass tests without changing all remaing direct deprecations

### CODE REVIEW

**Comment by bresam** [comment]
Hi @Chris53897 
Sorry that it took so long, didn't work on that google maps stuff since a long time.
I'll merge your PR partially into v6 branch.

And thank you very much for participating

**Comment by bresam** [comment]
@Chris53897 most of it is now merged to v6 branch

**Comment by Chris53897** [comment]
@bresam Thanks.
What is the best way to contribute?
Fork from 6.x and send PR against that branch?

Make 6.x an alias for master/main?

**Comment by bresam** [comment]
@Chris53897 if you like to contribute it would be nice to fork from "v6" branch and make PR's.

master is already on 6.0.0 deployed with my latest changes for sf6, so you can install e.g. "^6.0" with composer now.
"v6" branch is currently installable with composer by "v6.x-dev"

Thank you for being almost the only contributor on this project.
Must ask :-), would you like to join as another maintainer?

**Comment by Chris53897** [comment]
I will try to get it working with symfony 7. We already migrated our projects to symfony 7 ;)
After that we can decide if i become a maintainer.
I can only support repos that i use in real projects.

**Comment by bresam** [comment]
For me it's kind the same.
We used egeloen's google-map stuff for a project at work and when it got outdated i decided to maintain it.
Currently i'm updating the customer project to sf6, thats the reason why i got time to work on it.

**Pull request closed without merging**
